name: Build and Release

on:
  release: # Trigger workflow on creating a release
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Checkout code without .git
        with:
          fetch-depth: 0  # Only fetch the latest commit, excluding history
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies 
        run: npm install terser
      - name: Minify JavaScript  # Minify JavaScript file
        run: |
          terser public/js/fd-bb-inline-svg.js -o public/js/fd-bb-inline-svg.min.js
      - name: Update PHP file path
        run: |
          sed -i 's/public\/js\/fd-bb-inline-svg.js/public\/js\/fd-bb-inline-svg.min.js/g' fd-bb-inline-svg.php  # Replace string with minified path
      - name: Create archive  # Create a zip archive
        run: zip -r fd-bb-inline-svg.zip .
      - name: Upload zip to release  # Upload the zip to the release assets
        uses: actions/upload-artifact@v3
        with:
          name: plugin-archive
          path: fd-bb-inline-svg.zip
  upload-release-asset:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: plugin-archive  # Download artifact uploaded by build workflow
          path: release-assets 
      - uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.repos.upload_url }}/${{ github.sha }}/assets
          asset_name: fd-bb-inline-svg.zip 
          file: release-assets/fd-bb-inline-svg.zip
          content_type: application/zip
          tag_name: ${{ github.ref }}