name: Release Workflow

on:
  release:
    types: [created]

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
      
    - name: Minify JS Asset
      run: |
        npm install -g uglify-js
        uglifyjs /public/js/fd-bb-inline-svg.js -o /public/js/fd-bb-inline-svg.min.js
        
    - name: Update Reference in Plugin File
      run: |
        sed -i 's/public\/js\/fd-bb-inline-svg.js/public\/js\/fd-bb-inline-svg.min.js/g' fd-bb-inline-svg.php  # Replace string with minified path
      
    - name: Zip Codebase
      run: zip -r fd-bb-inline-svg.zip .
      
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./fd-bb-inline-svg.zip
        asset_name: fd-bb-inline-svg.zip
        asset_content_type: application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
